### ISSUE TITLE
US #13 Our Communities

### ISSUE THREAD

**Issue by Will-Hsu** [Will-Hsu/cses_webdev#121]
Implement the "Our Communities" component on the About page according to the Figma design: https://www.figma.com/file/UTEM8I95zldBmcZYv9uVHw/CSES-Website?type=design&node-id=0-1&mode=design&t=yDdCFWvXFc6BbmaN-0
Be sure to make it responsive on mobile devices too (we can discuss more on the layout for mobile view).

**Comment by ssyquia** [comment]
Everyone accessing the CSES website would see this new section. The goal is to make an "Our Communities" section in the CSES About page to inform the user of the different tech communities under CSES. This milestone will be considered a success if the design matches the mockup created on Figma and is responsive across all devices. There should be no need for any external dependencies. Sancho and Ganesh will be responsible for the task of high importance. It would take several meetings over the two weeks to complete this task.

**Comment by ssyquia** [comment]
[https://github.com/Will-Hsu/cses_webdev/pull/137](url)
